version: '3'

services: 
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes: 
      - ./app:/usr/src/app
    restart: on-failure 
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"


   